els-ASAP auto commit file/tag netcf-0.2.8-1.el7.src.rpm

diff --git a/src/netcf.spec.in b/src/netcf.spec.in
--- a/src/netcf.spec.in
+++ b/src/netcf.spec.in
@@ -9,10 +9,25 @@ URL:            https://fedorahosted.org/netcf/
 Source0:        https://fedorahosted.org/released/%{name}/%{name}-%{version}.tar.gz
 BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
 
+# Patches
+# One patch per line, in this format:
+# Patch001: file1.patch
+# Patch002: file2.patch
+# ...
+#
+# The patches will automatically be put into the build source tree
+# during the %prep stage (using git, which is now required for an rpm
+# build)
+#
+
 # Default to skipping autoreconf.  Distros can change just this one
 # line (or provide a command-line override) if they backport any
 # patches that touch configure.ac or Makefile.am.
 %{!?enable_autotools:%define enable_autotools 0}
+
+# git is used to build a source tree with patches applied (see the
+# %prep section)
+BuildRequires: git
 
 # Fedora 20 / RHEL-7 are where netcf first uses systemd. Although earlier
 # Fedora has systemd, netcf still used sysvinit there.
@@ -23,11 +38,10 @@ BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
 %endif
 
 %if %{with_systemd}
-BuildRequires: systemd-units
-Requires(post): systemd-units
-Requires(post): systemd-sysv
-Requires(preun): systemd-units
-Requires(postun): systemd-units
+BuildRequires: systemd
+Requires(post): systemd
+Requires(preun): systemd
+Requires(postun): systemd
 %endif
 %if 0%{?enable_autotools}
 BuildRequires: autoconf
@@ -88,6 +102,42 @@ The libraries for %{name}.
 %prep
 %setup -q
 
+# Patches have to be stored in a temporary file because RPM has
+# a limit on the length of the result of any macro expansion;
+# if the string is longer, it's silently cropped
+%{lua:
+    tmp = os.tmpname();
+    f = io.open(tmp, "w+");
+    count = 0;
+    for i, p in ipairs(patches) do
+        f:write(p.."\n");
+        count = count + 1;
+    end;
+    f:close();
+    print("PATCHCOUNT="..count.."\n")
+    print("PATCHLIST="..tmp.."\n")
+}
+
+git init -q
+git config user.name rpm-build
+git config user.email rpm-build
+git config gc.auto 0
+git add .
+git commit -q -a --author 'rpm-build <rpm-build>' \
+           -m '%{name}-%{version} base'
+
+COUNT=$(grep '\.patch$' $PATCHLIST | wc -l)
+if [ $COUNT -ne $PATCHCOUNT ]; then
+    echo "Found $COUNT patches in $PATCHLIST, expected $PATCHCOUNT"
+    exit 1
+fi
+if [ $COUNT -gt 0 ]; then
+    xargs git am <$PATCHLIST || exit 1
+fi
+echo "Applied $COUNT patches"
+rm -f $PATCHLIST
+
+
 %build
 %if %{with_libnl1}
 %define _with_libnl1 --with-libnl1
@@ -109,13 +159,9 @@ The libraries for %{name}.
 make %{?_smp_mflags}
 
 %install
-rm -rf $RPM_BUILD_ROOT
 make install DESTDIR=$RPM_BUILD_ROOT SYSTEMD_UNIT_DIR=%{_unitdir} \
      INSTALL="%{__install} -p"
-find $RPM_BUILD_ROOT -name '*.la' -exec rm -f {} ';'
-
-%clean
-rm -rf $RPM_BUILD_ROOT
+find $RPM_BUILD_ROOT -name '*.la' -delete
 
 %preun libs
 
@@ -145,12 +191,10 @@ fi
 %endif
 
 %files
-%defattr(-,root,root,-)
 %{_bindir}/ncftool
 %{_mandir}/man1/ncftool.1*
 
 %files libs
-%defattr(-,root,root,-)
 %{_datadir}/netcf
 %{_libdir}/*.so.*
 %if %{with_systemd}
@@ -162,13 +206,25 @@ fi
 %doc AUTHORS COPYING NEWS
 
 %files devel
-%defattr(-,root,root,-)
 %doc
 %{_includedir}/*
 %{_libdir}/*.so
 %{_libdir}/pkgconfig/netcf.pc
 
 %changelog
+* Wed Apr 08 2015 Laine Stump <laine@redhat.com> - 0.2.8-1
+ - Fix build on systems with newer libnl3 that doesn't
+   #include <linux/if.h>
+
+* Fri Apr 03 2015 Laine Stump <laine@redhat.com> - 0.2.7-1
+ - resolve CVE-2014-8119
+ - support multiple IPv4 addresses in interface config (redhat driver)
+ - allow static IPv4 config simultaneous with DHCPv4 (redhat driver)
+ - recognize IPADDR0/NETMASK0/PREFIX0
+ - remove extra quotes from IPV6ADDR_SECONDARIES (redhat+suse drivers)
+ - miscellaneous systemd service fixes
+ - use git to apply patches in rpm specfile
+
 * Fri Aug 22 2014 Laine Stump <laine@redhat.com> - 0.2.6-1
  - allow interleaved elements in interface XML schema
  - allow <link> element in vlan and bond interfaces
